#language: generic
sudo: required

services:
    - docker

before_install:
    - docker build -t calavan/docker-react -f Dockerfile.dev .

script:
    - docker run calavan/docker-react npm run test -- --coverage
#    - docker run -e CI=true calavan/docker-react npm run test
